name: build

on: [push]

jobs:
  ci:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.4.x', '2.5.x', '2.6.x']

    steps:
    - uses: actions/checkout@v1

    - name: set up ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: setup bundler
      run: |
        gem install bundler

    - name: install
      run: |
        ./install.sh
